apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: product-catalog-app
  labels:
    commit: 3bf0058350be94d19951a1182c221a1b20b245c1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-catalog-app
  template:
    metadata:
      labels:
        app: product-catalog-app
        commit: 3bf0058350be94d19951a1182c221a1b20b245c1
    spec:
      containers:
      - name: product-catalog-app-container
        image: kuzdo/alpha-office-product-catalog:master-3bf0058350be94d19951a1182c221a1b20b245c1
        imagePullPolicy: Always
        ports:
        - name: pc-app-port
          containerPort: 80
          protocol: TCP
      imagePullSecrets:
        - name: wercker
---
apiVersion: v1
kind: Service
metadata:
  name: product-catalog-service
  labels:
    app: product-catalog-app
    commit: 3bf0058350be94d19951a1182c221a1b20b245c1
spec:
  ports:
  - port: 30000
    targetPort: 80
  selector:
    app: product-catalog-app
    commit: 3bf0058350be94d19951a1182c221a1b20b245c1
  type: LoadBalancer
---
